Made gitleaks scan work on windows
leaktk/scanner pull request #11
Opened 2023-03-24 04:58 UTC by thewizzy

Windows does not have stdout, which it was using.

Output to a file `gitleaks-results.json` in the scan dir. This made the most sense as it is removed after scanning any way and very very unlikely to have a name clash. If it does clash it is written after the scan is performed and will be overwritten with valid scan result data.

Scan results are cleaned after the scan is complete and results have been consumed.

Also added a few more defaults to make testing defaults across platforms easier.

2023-03-24 11:38 UTC, bplaxco commented
@thewizzy looks good. The one thing I want to look at tweaking is dropping the results inside the repo. If someone was using it to scan a lot of local repos, I wouldn't want to dirty up their repos. I'm working on something [here](https://github.com/leaktk/scanner/pull/9) that should give you a space to put them. This morning I realized there's a bug on that branch for local repos, I'm going to try to fix that and merge it in Wed. After that you can use something like  `workspace.results_dir` as a tmp place to write files and they won't be in the repo. :+1:

2023-03-25 22:58 UTC, thewizzy commented
@bplaxco Thanks for the feedback. I will wait until workspaces is merged and then rejig this. That is a very good idea, I had not thought of the local repos use case.

2023-04-04 01:12 UTC, bplaxco requested changes
It looks like there may be the one issue with the shasum string having trailing spaces, but other than that, I think it looks good ^_^

2023-04-04 02:14 UTC, thewizzy commented on src/config.rs
> +                "d7a49162a15133958d3e4b8c0967581fe3069e81847978ad5b5f6903a9f6fa88  ",
Removed the two trailing. Had been fiddling with 8.16.1 support and swapped it back before pushing!
Good eye!

2023-04-06 01:52 UTC, bplaxco approved these changes
Looks good to me ^_^

2023-04-06 01:54 UTC, merged